### PR TITLE
chore(deps): Update Flutter 3.13 & Yaru

### PR DESCRIPTION
**Pull request by cnihelton**
CI will keep failing otherwise. Soon other repos that depend on this will fail as well.

### CODE REVIEW

**Review by Feichtmeier — APPROVED** [review]

**Review by kenvandine — APPROVED** [review]
LGTM

**Comment by d-loose** [comment]
@CarlosNihelton could we get this published as a new release on pub.dev?

**Comment by cnihelton** [comment]
I'm all for it, if the installer code base is ready for the upgrade ;)

**Comment by d-loose** [comment]
It won't automatically get the new version, since it still depends on yaru_widgets ^2.5.0. We'll need some small flutter 3.13 related fixes in ubuntu_test before we can bump the versions there, as far as I can tell.

**Pull request merged**
